name: Deploy Microservices  
 
on:  
  push:
    branches:
      - main
  workflow_dispatch:  
 
jobs:
 
  deploy:
    runs-on: ubuntu-latest
 
    env:
      VERSION: ${{ github.sha }}
   
 
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
 
      - name: setup azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
         
      - name: Settingup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
 
      - name: terraform init
        working-directory: ./Terraform
        run: terraform init
 
      - name: terraform plan
        working-directory: ./Terraform
        run: terraform plan
 
      - name: terraform apply
        working-directory: ./Terraform
        run: terraform apply -auto-approve
 
 
 
      - name: Getting ACR Name
        working-directory: ./Terraform
        run: |
          CONTAINER_REGISTRY=$(terraform-bin output -raw registry_name)
          echo "CONTAINER_REGISTRY=$CONTAINER_REGISTRY" >> $GITHUB_ENV
 
      - name: ACR login
        run: |
          echo ${{ secrets.CLIENT_SECRET }} | docker login ${{ env.CONTAINER_REGISTRY }}.azurecr.io -u ${{ secrets.CLIENT_ID }} --password-stdin
 
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
 
      - name: Make sh files executable
        working-directory: ./scripts/
        run: chmod +x *.sh
 
      - name: Building Docker images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./scripts/build-image.sh
 
 
      - name: Push Docker images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./scripts/push-image.sh
 
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group rg08 --name cluster08 --overwrite-existing
 
      - name: Attaching ACR to AKS
        run: az aks update -n cluster08 -g rg08 --attach-acr registry08
   
      - name: Deploy microservices
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./scripts/deploy.sh
 
      - run: sleep 60
 
      - name: Get kube details
        run: |
              kubectl get pods
              kubectl get deployments
              kubectl get services
 
